<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/quarto-syntax-highlighting-dark-9e15f8fb9e1f2f288bfbe28f6ca11029.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Stranger Syntax">
  <title>Mind-Flayer Patch v2</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #f8f8f2; background-color: #2e3440; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #f8f8f2; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #75715e; } /* Annotation */
    code span.at { color: #f92672; } /* Attribute */
    code span.bn { color: #ae81ff; } /* BaseN */
    code span.bu { color: #66d9ef; } /* BuiltIn */
    code span.cf { color: #f92672; } /* ControlFlow */
    code span.ch { color: #e6db74; } /* Char */
    code span.cn { color: #ae81ff; } /* Constant */
    code span.co { color: #75715e; } /* Comment */
    code span.cv { color: #75715e; } /* CommentVar */
    code span.do { color: #75715e; } /* Documentation */
    code span.dt { color: #66d9ef; font-style: italic; } /* DataType */
    code span.dv { color: #ae81ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #a6e22e; font-weight: bold; } /* Extension */
    code span.fl { color: #ae81ff; } /* Float */
    code span.fu { color: #a6e22e; } /* Function */
    code span.im { color: #f92672; } /* Import */
    code span.in { color: #f1fa8c; } /* Information */
    code span.kw { color: #f92672; } /* Keyword */
    code span.op { color: #f8f8f2; } /* Operator */
    code span.ot { color: #a6e22e; } /* Other */
    code span.pp { color: #f92672; } /* Preprocessor */
    code span.re { color: #75715e; } /* RegionMarker */
    code span.sc { color: #ae81ff; } /* SpecialChar */
    code span.ss { color: #e6db74; } /* SpecialString */
    code span.st { color: #e6db74; } /* String */
    code span.va { color: #f8f8f2; } /* Variable */
    code span.vs { color: #e6db74; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/theme/quarto-3a838ba4d842d7d9dc9c62596a7478fe.css">
  <link href="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="mermaid-theme" content="dark">
  <script src="presentation_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="presentation_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="presentation_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section class="quarto-title-block center">
  <h1 class="title">Mind-Flayer Patch v2</h1>
  <p class="subtitle">Adaptive Content Moderation Under Adversarial Constraints</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Stranger Syntax 
</div>
</div>
</div>

</section>
<section class="slide level2 center">
<h2>The Problem</h2>
<ul>
<li class="fragment">A large-scale platform is under attack</li>
<li class="fragment">Content causes <strong>real-world harm</strong> — not through lies, but through <strong>manipulation of context</strong></li>
<li class="fragment">Adversaries <strong>adapt in real time</strong> to detection strategies</li>
<li class="fragment">We must build a system that is <strong>defensible, cost-aware, and adaptive</strong></li>
</ul>
<aside class="notes">
<p>Emphasize that this isn’t about fake news detection — it’s about contextual manipulation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2 center">
<h2>The Constraints We Must Respect</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Constraint</th>
<th>What It Means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Signal Collapse</strong></td>
<td>Detection methods decay when overused</td>
</tr>
<tr class="even">
<td><strong>Partial Observability</strong></td>
<td>Content arrives in stages, not all at once</td>
</tr>
<tr class="odd">
<td><strong>Human Trust Budget</strong></td>
<td>Only <strong>20 human reviews/hour</strong></td>
</tr>
<tr class="even">
<td><strong>Multilingual Ambiguity</strong></td>
<td>Urdu, Roman Urdu, English — context-dependent</td>
</tr>
<tr class="odd">
<td><strong>Poisoned Feedback</strong></td>
<td>~15% of human labels are noisy or adversarial</td>
</tr>
<tr class="even">
<td><strong>Budget Reality</strong></td>
<td>PKR 50,000/month (~$175 USD) for everything</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2 center">
<h2>Mid-Challenge Update</h2>
<blockquote>
<p>“A large portion of harmful content is <strong>factually correct</strong>, but <strong>contextually misleading</strong>.”</p>
</blockquote>
<div class="fragment">
<p>Fact-checking alone is <strong>not enough</strong>.</p>
<p>The system must reason about <strong>framing, narrative, and selective presentation</strong>.</p>
</div>
</section>
<section class="slide level2 center">
<h2>Our Approach: 3-Stage Adaptive Pipeline</h2>
<div class="cell" data-reveal="true" data-fig-width="11" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["📨 User Submits Post"] --&gt; B["⚡ Stage 1: Keyword Scan\n&lt; 50ms | FREE"]
    B --&gt;|"0 hits"| S1["✅ Safe"]
    B --&gt;|"3+ hits"| H1["🚫 Auto-Remove"]
    B --&gt;|"1–2 hits"| C["🤖 Stage 2: Lightweight Claude\n~2s | ~$0.0002"]
    C --&gt;|"safe"| S2["✅ Safe"]
    C --&gt;|"harmful"| H2["🚫 Auto-Remove"]
    C --&gt;|"uncertain"| D["🔬 Stage 3: Detailed Claude\n~4s | ~$0.0004"]
    D --&gt;|"safe"| S3["✅ Safe"]
    D --&gt;|"harmful"| H3["🚫 Auto-Remove"]
    D --&gt;|"escalate"| E["👤 Human Review Queue\n20/hour budget"]

    style B fill:#166534,stroke:#4ade80,color:#fff
    style C fill:#854d0e,stroke:#facc15,color:#fff
    style D fill:#991b1b,stroke:#f87171,color:#fff
    style E fill:#1e3a5f,stroke:#60a5fa,color:#fff
    style S1 fill:#14532d,stroke:#4ade80,color:#4ade80
    style S2 fill:#14532d,stroke:#4ade80,color:#4ade80
    style S3 fill:#14532d,stroke:#4ade80,color:#4ade80
    style H1 fill:#7f1d1d,stroke:#f87171,color:#f87171
    style H2 fill:#7f1d1d,stroke:#f87171,color:#f87171
    style H3 fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section class="slide level2 smaller center">
<h2>Stage 1: Keyword Scan</h2>
<p><strong>Fast, free, multilingual first filter</strong></p>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell" data-reveal="true" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Incoming Post"] --&gt; B["Detect Language"]
    B --&gt; C["Scan Keywords\nEN + UR + Roman UR"]
    C --&gt;|"0 hits"| D["✅ Safe"]
    C --&gt;|"1–2 hits"| E["⚠️ Uncertain\n→ Stage 2"]
    C --&gt;|"3+ hits"| F["🚫 Harmful\nauto-remove"]

    style D fill:#14532d,stroke:#4ade80,color:#4ade80
    style E fill:#854d0e,stroke:#facc15,color:#fff
    style F fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Multilingual keywords:</strong></p>
<pre><code>English: kill, bomb, attack, terrorism...
Urdu:    قتل، بم، حملہ، دہشت، نفرت
Roman:   maar, qatal, bomb, hamla...</code></pre>
<p><strong>Language detection:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> urdu_chars <span class="op">&gt;</span> <span class="dv">30</span><span class="op">%</span>:</span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"urdu"</span></span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> roman_urdu_markers <span class="op">&gt;=</span> <span class="dv">2</span>:</span>
<span id="cb2-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"roman_urdu"</span></span>
<span id="cb2-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> <span class="st">"english"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></div>
<p><strong>Cost: $0.00 | Latency: &lt;50ms</strong></p>
</section>
<section class="slide level2 smaller center">
<h2>Stage 2: Lightweight AI Analysis</h2>
<p><strong>Context-aware detection with prompt rotation</strong></p>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell" data-reveal="true" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Uncertain Post\nfrom Stage 1"] --&gt; B{"Budget\nRemaining?"}
    B --&gt;|"No"| X["⚠️ Skip AI\n→ Escalate"]
    B --&gt;|"Yes"| C["Select Prompt\n(weighted random by decay)"]
    C --&gt; P1["safety_check_v1"]
    C --&gt; P2["context_analyzer_v1"]
    C --&gt; P3["narrative_detector_v1"]
    C --&gt; P4["framing_analyzer_v1"]
    C --&gt; P5["selective_presentation_v1"]
    P1 &amp; P2 &amp; P3 &amp; P4 &amp; P5 --&gt; D["Claude Haiku\nAnalysis"]
    D --&gt; E["Verdict + Confidence\n+ Manipulation Tactics"]

    style B fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style D fill:#854d0e,stroke:#facc15,color:#fff
    style X fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>What it detects beyond keywords:</strong></p>
<ul>
<li>Selective facts presented to mislead</li>
<li>Cherry-picked statistics without context</li>
<li>Emotional manipulation with real data</li>
<li>True statements made misleading by omission</li>
<li>Misleading juxtaposition</li>
</ul>
<p><strong>Budget gate:</strong> If monthly budget exceeded, skip AI → escalate to human.</p>
</div></div>
<p><strong>Model: Claude Haiku | Cost: ~$0.0002/call | Latency: ~2s</strong></p>
</section>
<section class="slide level2 smaller center">
<h2>Stage 3: Deep Analysis + Human Escalation</h2>
<p><strong>Full-context reasoning for the hardest cases</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Receives from Stage 2:</strong></p>
<ul>
<li>Original content + language</li>
<li>Stage 2 reasoning + verdict</li>
<li>Detected manipulation tactics</li>
</ul>
<p><strong>Analyzes:</strong></p>
<ul>
<li>Cultural/linguistic context</li>
<li>Satire vs.&nbsp;genuine threat</li>
<li>What context is <strong>missing</strong></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Critical principle:</strong></p>
<blockquote>
<p><em>“Content that is factually correct but deliberately omits important context <strong>IS</strong> harmful.”</em></p>
</blockquote>
<p><strong>If still uncertain → Escalate</strong></p>
<p>Creates a <code>ReviewItem</code> with full AI reasoning for human moderator.</p>
</div></div>
<p><strong>Model: Claude Haiku | Cost: ~$0.0004/call | Latency: ~4s</strong></p>
</section>
<section class="slide level2 center">
<h2>Constraint 1: Signal Collapse</h2>
<blockquote>
<p><em>“Every detection method becomes less effective if overused.”</em></p>
</blockquote>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Our solution: Detection method decay</strong></p>
<ul>
<li>Each prompt variant has a <strong>decay factor</strong> (1.0 → 0.1)</li>
<li>Every use reduces it by <strong>2%</strong></li>
<li>Selection is <strong>weighted random</strong> — overused methods picked less often</li>
<li>Minimum floor of <strong>10%</strong> — never fully excluded</li>
<li>Manual <strong>reset</strong> available when needed</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell" data-reveal="true" data-fig-width="5.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Method Pool\n5 prompt variants"] --&gt; B["Weighted Random\nSelection"]
    B --&gt; C["Selected Method\nruns analysis"]
    C --&gt; D["Record Usage\ndecay -= 2%"]
    D --&gt; E{"decay_factor\n&lt; 0.1?"}
    E --&gt;|"Yes"| F["Floor at 0.1\nnever excluded"]
    E --&gt;|"No"| G["Updated weight\nfor next selection"]
    F --&gt; A
    G --&gt; A

    style A fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style B fill:#1e1b4b,stroke:#a78bfa,color:#fff
    style D fill:#854d0e,stroke:#facc15,color:#fff
    style F fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div></div>
</section>
<section class="slide level2 center">
<h2>Constraint 2: Partial Observability</h2>
<blockquote>
<p><em>“Content arrives in stages — waiting for full data violates latency.”</em></p>
</blockquote>
<div class="cell" data-reveal="true" data-fig-width="11" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph S1["⚡ Stage 1 — sync, &lt;50ms"]
        A1["Metadata\n+ Keywords"]
    end
    subgraph S2["🤖 Stage 2 — async, ~2s"]
        A2["Partial Content\n1 AI Prompt"]
    end
    subgraph S3["🔬 Stage 3 — async, ~4s"]
        A3["Full Context\n+ Prior Reasoning"]
    end

    A1 --&gt;|"uncertain"| A2
    A2 --&gt;|"uncertain"| A3

    A1 --&gt;|"clear verdict"| D1["✅ Done"]
    A2 --&gt;|"confident"| D2["✅ Done"]
    A3 --&gt;|"decides or escalates"| D3["✅ Done"]

    style S1 fill:#166534,stroke:#4ade80,color:#fff
    style S2 fill:#854d0e,stroke:#facc15,color:#fff
    style S3 fill:#991b1b,stroke:#f87171,color:#fff
    style D1 fill:#14532d,stroke:#4ade80,color:#4ade80
    style D2 fill:#14532d,stroke:#4ade80,color:#4ade80
    style D3 fill:#14532d,stroke:#4ade80,color:#4ade80
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Key:</strong> Stages 2 &amp; 3 run as <strong>background tasks</strong> — the user gets an immediate response. Post status updates asynchronously.</p>
</section>
<section class="slide level2 center">
<h2>Constraint 3: Human Trust Budget</h2>
<blockquote>
<p><em>“Only 20 human reviews per hour.”</em></p>
</blockquote>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell" data-reveal="true" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Stage 3 Escalates Post"] --&gt; B["Review Queue"]
    B --&gt; C{"Reviews this\nhour &lt; 20?"}
    C --&gt;|"Yes"| D["Moderator Reviews\n+ AI reasoning\n+ manipulation tactics"]
    D --&gt; E["Approve ✅"]
    D --&gt; F["Reject 🚫"]
    C --&gt;|"No"| G["⏳ HTTP 429\nBudget Exhausted\nWait for next hour"]

    style B fill:#1e3a5f,stroke:#60a5fa,color:#fff
    style C fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style E fill:#14532d,stroke:#4ade80,color:#4ade80
    style F fill:#7f1d1d,stroke:#f87171,color:#f87171
    style G fill:#854d0e,stroke:#facc15,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Review queue provides:</strong></p>
<ul>
<li>Original post content</li>
<li>Full AI reasoning from Stage 2 + 3</li>
<li>Detected manipulation tactics</li>
<li>Approve / Reject with reviewer notes</li>
</ul>
<p><strong>Most content never needs a human.</strong> The 3-stage pipeline filters aggressively — only truly ambiguous cases escalate.</p>
</div></div>
</section>
<section class="slide level2 center">
<h2>Constraint 4: Multilingual Ambiguity</h2>
<blockquote>
<p><em>“yeh fire hai” — praise or threat?</em></p>
</blockquote>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Language detection:</strong></p>
<ul>
<li><strong>Urdu script</strong> (Unicode <code>\u0600-\u06FF</code>)</li>
<li><strong>Roman Urdu</strong> markers: <em>hai, nahi, yeh, kya, mein…</em></li>
<li>Fallback: <strong>English</strong></li>
</ul>
<p>Language passed to every AI prompt for context-aware analysis.</p>
</div><div class="column" style="width:50%;">
<p><strong>How we avoid hard classification:</strong></p>
<ul>
<li>Stage 2/3 prompts explicitly consider cultural context</li>
<li>“uncertain” is a <strong>valid verdict</strong> — no forced binary</li>
<li>Ambiguous content escalates to human reviewers who understand nuance</li>
</ul>
</div></div>
<div class="fragment">
<p><strong>We penalize overconfidence, not uncertainty.</strong></p>
</div>
</section>
<section class="slide level2 center">
<h2>Constraint 5: Poisoned Feedback Loop</h2>
<blockquote>
<p><em>“~15% of human labels are noisy or adversarial.”</em></p>
</blockquote>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell" data-reveal="true" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Human Submits\nReview Decision"] --&gt; B["Log: reviewer_id\ntimestamp, note"]
    B --&gt; C["Store alongside\nAI reasoning"]
    C --&gt; D["Audit Trail\n(no auto-retrain)"]
    D --&gt; E["Future: Label\nConfidence Scoring"]

    N["⚠️ ~15% Noisy Labels"] -.-&gt;|"detected via\ndiscrepancy audit"| D

    style A fill:#1e3a5f,stroke:#60a5fa,color:#fff
    style D fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style N fill:#7f1d1d,stroke:#f87171,color:#f87171
    style E fill:#14532d,stroke:#4ade80,color:#4ade80
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Our approach: Audit trail, not blind trust</strong></p>
<ul>
<li>Every human review is <strong>logged</strong> with reviewer ID, timestamp, and notes</li>
<li>AI reasoning is <strong>preserved alongside</strong> human decisions</li>
<li>No automatic retraining on raw labels</li>
<li>Discrepancies between AI and human can be audited</li>
<li>Foundation for future <strong>label confidence scoring</strong></li>
</ul>
</div></div>
</section>
<section class="slide level2 center">
<h2>Constraint 6: Budget Reality</h2>
<blockquote>
<p><em>“PKR 50,000/month (~$175 USD) for everything.”</em></p>
</blockquote>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell" data-reveal="true" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Claude API Call"] --&gt; B["Log to cost_logs\ntokens × rate"]
    B --&gt; C["Monthly Spend\nTracker"]
    C --&gt; D{"spent &lt;\n$175?"}
    D --&gt;|"Yes"| E["✅ Proceed\nwith AI analysis"]
    D --&gt;|"No"| F["⛔ Budget Gate\nKeyword-only mode\n+ Human escalation"]

    style D fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style E fill:#14532d,stroke:#4ade80,color:#4ade80
    style F fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Estimated monthly cost:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Component</th>
<th>Volume</th>
<th>Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stage 1 (keywords)</td>
<td>Unlimited</td>
<td>$0</td>
</tr>
<tr class="even">
<td>Stage 2 (Haiku)</td>
<td>~50K calls</td>
<td>~$10</td>
</tr>
<tr class="odd">
<td>Stage 3 (Haiku)</td>
<td>~10K calls</td>
<td>~$4</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td><strong>~$14/mo</strong></td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>$14 of $175 = 8% utilization</strong></p>
<p>Room for <strong>12x growth</strong> before budget pressure.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Why a Pipeline?</h2>
<p><strong>The core question:</strong> How should content flow through the system?</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Alternatives we rejected:</strong></p>
<ol type="1">
<li><strong>Single-model classification</strong> — Send everything to Claude
<ul>
<li>Costs ~$0.0004/post. At 100K posts/mo = $40. Feasible but wasteful — most content is obviously safe or obviously harmful</li>
<li>No adaptation. One prompt = one signal = easy for adversaries to learn</li>
</ul></li>
<li><strong>Ensemble of models voting</strong> — Run 3 models, take majority
<ul>
<li>3x cost for every post. Blows budget at scale</li>
<li>Adversary only needs to fool 2 of 3</li>
</ul></li>
<li><strong>Human-first triage</strong> — Humans scan everything, AI assists
<ul>
<li>20 reviews/hour = 480/day. Platform likely has thousands of posts. Impossible</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>Why staged pipeline wins:</strong></p>
<ul>
<li><strong>Cost cascade</strong>: Most content exits at Stage 1 (free). Only uncertain cases pay for AI. Only the hardest cases use expensive Stage 3</li>
<li><strong>Latency cascade</strong>: Easy decisions are instant. Hard decisions take longer — but that’s acceptable because they’re genuinely hard</li>
<li><strong>Each stage adds different information</strong>: keywords → single AI perspective → full context reasoning</li>
<li><strong>Maps directly to partial observability constraint</strong>: Stage 1 = metadata, Stage 2 = partial content, Stage 3 = full content</li>
</ul>
</div></div>
<div class="fragment">
<p><strong>The pipeline is not just an optimization — it’s the natural shape of the problem.</strong></p>
</div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Why These Thresholds?</h2>
<p><strong>Stage 1: Why 3+ keywords = auto-remove?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The tradeoff:</strong></p>
<ul>
<li><strong>Too low (1 hit)</strong>: “The bomb pasta recipe was killer” gets removed. High false positives → users lose trust in the platform</li>
<li><strong>Too high (5+ hits)</strong>: Genuinely harmful content with 3-4 harmful terms slips through to Stage 2, wasting AI budget</li>
<li><strong>3 hits</strong>: A post with 3 harmful keywords across 3 languages is almost certainly not accidental. False positive rate is low enough to justify auto-action</li>
</ul>
<p><strong>Why 0 hits = safe (skip AI)?</strong></p>
<p>If a post contains zero matches across 24+ keywords in 3 languages, the probability it’s harmful via explicit content is very low. Contextual manipulation (no keywords) is harder to detect at Stage 1 — but that’s exactly what Stage 2’s prompt rotation handles.</p>
</div><div class="column" style="width:50%;">
<p><strong>The honest gap:</strong></p>
<p>Contextually misleading content with zero harmful keywords <strong>will bypass Stage 1</strong>. This is by design.</p>
<ul>
<li>“Unemployment rose 50% in Karachi” (true but cherry-picked from a recovery quarter)</li>
<li>Contains no harmful keywords</li>
<li>Passes Stage 1 as “safe”</li>
</ul>
<p><strong>Our mitigation:</strong> This is why the mid-challenge update matters. We added 5 manipulation-focused prompt variants specifically for content that is “factually correct but contextually misleading.” But these only run in Stage 2 — and Stage 2 only runs on uncertain content from Stage 1.</p>
<p><strong>We accept this gap</strong> because the alternative (running AI on every post) costs 12x more and doesn’t respect the budget constraint.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Why Prompt Rotation?</h2>
<p><strong>The problem:</strong> If we use one prompt, adversaries learn exactly what it looks for and craft content to avoid it.</p>
<div class="cell" data-reveal="true" data-fig-width="11" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph Problem["❌ Single Prompt — Adversary Learns Pattern"]
        P1["Always check for\nexplicit harm"] --&gt; ADV1["Adversary avoids\nexplicit terms"] --&gt; FAIL["Content passes\nevery time"]
    end

    subgraph Solution["✅ Rotating Prompts — Adversary Can't Predict"]
        R1["safety_check_v1\n(explicit harm)"]
        R2["context_analyzer_v1\n(framing bias)"]
        R3["narrative_detector_v1\n(cherry-picked data)"]
        R4["framing_analyzer_v1\n(loaded language)"]
        R5["selective_presentation_v1\n(missing context)"]
        R1 &amp; R2 &amp; R3 &amp; R4 &amp; R5 --&gt; WIN["Adversary must evade\nALL 5 perspectives"]
    end

    style Problem fill:#7f1d1d,stroke:#f87171,color:#fff
    style Solution fill:#14532d,stroke:#4ade80,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Key insight:</strong> Each prompt variant targets a <strong>different manipulation technique</strong>. An adversary who learns to bypass “explicit harm detection” still gets caught by “selective presentation detection.”</p>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Why Decay, Not Rotation?</h2>
<p><strong>Alternative considered:</strong> Simple round-robin (cycle through prompts 1→2→3→4→5→1…)</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Why round-robin fails:</strong></p>
<ul>
<li><strong>Predictable.</strong> Adversary observes which posts get caught and when. After 5 posts, they know the cycle</li>
<li><strong>No memory.</strong> If prompt 3 catches 90% of current attacks, round-robin still only uses it 20% of the time</li>
<li><strong>No degradation signal.</strong> No way to know when a method is becoming ineffective</li>
</ul>
<p><strong>Why weighted random with decay wins:</strong></p>
<ul>
<li><strong>Unpredictable.</strong> Even with identical content, the selected prompt varies</li>
<li><strong>Self-adjusting.</strong> Overused methods naturally get selected less. Fresh methods get more weight</li>
<li><strong>Observable.</strong> Dashboard shows decay factors — operators can see system health in real-time</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>The decay math:</strong></p>
<ul>
<li><code>decay_rate = 0.02</code> (2% per use)</li>
<li><code>min_decay = 0.1</code> (10% floor)</li>
<li>After 45 uses: <code>1.0 - (45 × 0.02) = 0.10</code> (floor)</li>
</ul>
<p><strong>Why 2% and not 5% or 10%?</strong></p>
<ul>
<li><strong>5-10%</strong>: Methods hit floor after 10-18 uses. Too aggressive — methods rotate too fast, the system becomes unstable</li>
<li><strong>1%</strong>: Takes 90 uses to reach floor. Too slow — adversary has too many attempts against the same method</li>
<li><strong>2%</strong>: ~45 uses per method. With 5 methods at equal usage, that’s ~225 total posts before any method hits floor. Reasonable for a daily cycle</li>
</ul>
<p><strong>Why a floor of 10%, not 0%?</strong></p>
<p>Excluding a method entirely means adversaries know it’s gone. A 10% chance means it could still appear — maintaining uncertainty.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Budget Strategy</h2>
<p><strong>The budget is the hardest constraint.</strong> $175/mo sounds generous until you do the math.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Why Claude Haiku (not Sonnet/Opus)?</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th>Input/1K tok</th>
<th>Output/1K tok</th>
<th>Cost per call</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Haiku</td>
<td>$0.00025</td>
<td>$0.00125</td>
<td>~$0.0002</td>
</tr>
<tr class="even">
<td>Sonnet</td>
<td>$0.003</td>
<td>$0.015</td>
<td>~$0.003</td>
</tr>
<tr class="odd">
<td>Opus</td>
<td>$0.015</td>
<td>$0.075</td>
<td>~$0.015</td>
</tr>
</tbody>
</table>
<ul>
<li>Sonnet = <strong>15x</strong> more expensive → only ~58K calls/mo</li>
<li>Opus = <strong>75x</strong> more expensive → only ~11K calls/mo</li>
<li>Haiku = <strong>~875K calls/mo</strong> budget capacity</li>
</ul>
<p><strong>Tradeoff:</strong> Haiku is less capable at nuanced reasoning. We compensate with <strong>specific, targeted prompts</strong> that tell it exactly what to look for, rather than asking for general analysis.</p>
</div><div class="column" style="width:50%;">
<p><strong>Why not fine-tune a local model?</strong></p>
<ul>
<li>Fine-tuning cost: $500+ for a useful model. Exceeds 3 months of budget</li>
<li>Hosting cost: GPU instance ~$100-500/mo. Eats entire budget</li>
<li>Maintenance: Retraining as adversaries adapt requires ongoing compute</li>
<li>With Haiku at ~$14/mo, we have <strong>$161 of headroom</strong> for spikes</li>
</ul>
<p><strong>Graceful degradation when budget runs out:</strong></p>
<pre><code>Budget OK    → Stage 1 + 2 + 3 (full pipeline)
Budget tight → Stage 1 + 2 only (skip Stage 3)
Budget gone  → Stage 1 only (keywords + human)</code></pre>
<p>The system never fully stops. It degrades to a less capable but still functional mode. Keywords still catch obvious harm. Humans still review escalated content.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Human Review Budget</h2>
<p><strong>20 reviews/hour = the system’s most precious resource.</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Why enforce at submission time, not at queue entry?</strong></p>
<ul>
<li><strong>Queue entry enforcement</strong>: Posts pile up in queue, moderator sees them but can’t act. Frustrating UX, false sense of backlog</li>
<li><strong>Submission enforcement</strong>: Moderator sees exactly what they can act on. No phantom queue. HTTP 429 is clear feedback: “come back next hour”</li>
</ul>
<p><strong>Why not prioritize which posts humans see?</strong></p>
<p>We considered scoring escalated posts by confidence and showing lowest-confidence first. We rejected this because:</p>
<ul>
<li>Adds complexity without clear benefit at 20/hr</li>
<li>Low-confidence posts aren’t necessarily higher impact</li>
<li>FIFO is transparent — moderators trust it</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>How AI reasoning helps humans:</strong></p>
<p>Each review item shows:</p>
<ul>
<li>The AI’s <strong>verdict</strong> from Stage 2 and 3</li>
<li>The AI’s <strong>reasoning</strong> (natural language explanation)</li>
<li>Detected <strong>manipulation tactics</strong> (cherry-picked stats, loaded language, etc.)</li>
</ul>
<p><strong>This is deliberate.</strong> A moderator reviewing “yeh fire hai” without context is guessing. A moderator reviewing it with “AI detected possible threat language, but confidence is low because ‘fire’ is commonly used as praise in Roman Urdu” makes a <strong>better decision faster</strong>.</p>
<p><strong>The tradeoff:</strong> AI reasoning could bias the human. We accept this because:</p>
<ul>
<li>Unbiased humans with no context make worse decisions</li>
<li>The 15% noise rate already means human labels aren’t pure</li>
<li>AI reasoning is logged alongside human decisions for auditing</li>
</ul>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Multilingual Approach</h2>
<p><strong>Why heuristic language detection, not a library?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Alternatives considered:</strong></p>
<ol type="1">
<li><strong>langdetect / fasttext</strong>: Good for clean text. Fails on Roman Urdu (looks like misspelled English), code-mixed text (“yeh so cool hai”), and short posts</li>
<li><strong>Google Translate API</strong>: Costs money per call. Adds latency. Eats into $175 budget</li>
<li><strong>Let Claude detect language</strong>: Already paying for AI in Stage 2. But Stage 1 needs language for keyword selection <em>before</em> Claude runs</li>
</ol>
<p><strong>Our heuristic:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Urdu script = Urdu (high confidence)</span></span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> urdu_chars <span class="op">&gt;</span> <span class="dv">30</span><span class="op">%</span> of text → <span class="st">"urdu"</span></span>
<span id="cb4-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Roman Urdu markers (hai, nahi, yeh, kya, mein...)</span></span>
<span id="cb4-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> roman_urdu_words <span class="op">&gt;=</span> <span class="dv">2</span> → <span class="st">"roman_urdu"</span></span>
<span id="cb4-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Fallback</span></span>
<span id="cb4-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span> → <span class="st">"english"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column" style="width:50%;">
<p><strong>Tradeoffs we accept:</strong></p>
<ul>
<li><strong>False positive:</strong> “Yeh brand hai best” detected as Roman Urdu. Harmless — Stage 2 prompt includes language context either way</li>
<li><strong>False negative:</strong> Single Roman Urdu word in English text (“that’s a jugaar solution”) detected as English. Low risk — Claude understands code-mixing regardless</li>
<li><strong>30% threshold for Urdu:</strong> Lower catches more Urdu but misclassifies Arabic. Higher misses short Urdu posts. 30% is a pragmatic middle ground</li>
</ul>
<p><strong>Why this matters for moderation:</strong></p>
<p>“yeh fire hai” classified correctly as Roman Urdu triggers <strong>cultural context analysis</strong> in Stage 2/3 prompts. Misclassified as English, Claude might miss that “fire” is common praise in South Asian slang.</p>
<p><strong>We don’t force binary classification.</strong> “Uncertain” language → AI gets the full text and figures it out.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: Poisoned Labels</h2>
<p><strong>15% noise means 1 in ~7 human labels is wrong. This is a real threat.</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>What we do:</strong></p>
<ul>
<li><strong>Store everything.</strong> Every human decision + AI reasoning + timestamps + reviewer identity</li>
<li><strong>Never auto-retrain.</strong> Human labels do not flow back into the system’s detection logic</li>
<li><strong>Preserve AI reasoning alongside human decisions.</strong> If AI said “harmful” and human said “safe,” that discrepancy is visible</li>
</ul>
<p><strong>Why this is enough for now:</strong></p>
<p>The problem statement says “blindly trusting labels can reinforce harmful patterns.” Our system <strong>doesn’t trust labels at all</strong> — it uses them for final post disposition only, not for learning.</p>
</div><div class="column" style="width:50%;">
<p><strong>What we’d add with more time:</strong></p>
<div class="cell" data-reveal="true" data-fig-width="5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["Human Label\nSubmitted"] --&gt; B["Compare to\nAI Prediction"]
    B --&gt; C{"Agreement?"}
    C --&gt;|"Yes"| D["High confidence\nlabel"]
    C --&gt;|"No"| E["Flag for\nsecond review"]
    E --&gt; F["Track reviewer\ndisagreement rate"]
    F --&gt; G{"Reviewer noise\n&gt; 30%?"}
    G --&gt;|"Yes"| H["Reduce reviewer\ntrust weight"]
    G --&gt;|"No"| I["Accept as\nlegitimate disagreement"]

    style E fill:#854d0e,stroke:#facc15,color:#fff
    style H fill:#7f1d1d,stroke:#f87171,color:#f87171
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Per-reviewer trust scoring.</strong> Track each reviewer’s agreement rate with AI. Reviewers who consistently disagree with high-confidence AI verdicts get flagged. This catches coordinated adversarial labeling.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Design Reasoning: What We Chose NOT to Build</h2>
<p><strong>Simplicity with strong reasoning is valued. Here’s what we deliberately left out.</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>No ML training pipeline</strong></p>
<ul>
<li>Fine-tuning requires labeled data. Our labels have 15% noise</li>
<li>Training costs exceed monthly budget</li>
<li>A pre-trained LLM with good prompts outperforms a small fine-tuned model on nuanced tasks like context manipulation</li>
<li><strong>Decision:</strong> Use Claude’s general reasoning ability + specific prompts</li>
</ul>
<p><strong>No image/video analysis</strong></p>
<ul>
<li>Problem statement focuses on text content and framing</li>
<li>Image analysis (OCR, deepfake detection) adds cost and complexity</li>
<li>Haiku’s vision capability exists but costs more per call</li>
<li><strong>Decision:</strong> Text-only pipeline. Acknowledge gap in failure modes</li>
</ul>
<p><strong>No real-time adversary fingerprinting</strong></p>
<ul>
<li>Tracking posting patterns (timing, accounts, networks) is powerful but requires significant infrastructure</li>
<li>Rate limiting and user-level analysis need Redis, background workers, graph databases</li>
<li><strong>Decision:</strong> Out of scope for budget. Acknowledge as future work</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>No Celery / Redis / message queue</strong></p>
<ul>
<li>FastAPI <code>BackgroundTasks</code> is simpler and sufficient</li>
<li>No persistent queue means if server restarts, in-flight moderation is lost</li>
<li><strong>Tradeoff:</strong> Simplicity over durability. For a demo, this is fine. For production, we’d add Redis</li>
</ul>
<p><strong>No confidence calibration</strong></p>
<ul>
<li>Claude returns confidence scores (0.0-1.0) but they’re not calibrated</li>
<li>A “0.7 confidence” doesn’t mean 70% accuracy</li>
<li><strong>Tradeoff:</strong> We use confidence for logging/display, not for hard decisions. Verdicts (safe/harmful/uncertain) drive logic, not scores</li>
</ul>
<p><strong>No A/B testing of prompts</strong></p>
<ul>
<li>We could run two prompts on the same content and compare</li>
<li>2x cost per post. Not justified given budget headroom</li>
<li><strong>Decision:</strong> Rely on decay mechanism to naturally rotate. Add A/B testing if detection quality drops</li>
</ul>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>The Tradeoff Map</h2>
<p>Every design decision is a tradeoff. Here’s how they connect:</p>
<div class="cell" data-reveal="true" data-fig-width="11" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    COST["💰 Lower Cost"] ---|"tension"| ACC["🎯 Higher Accuracy"]
    ACC ---|"tension"| SPEED["⚡ Lower Latency"]
    SPEED ---|"tension"| ADAPT["🔄 Adaptability"]
    ADAPT ---|"tension"| SIMPLE["📐 Simplicity"]
    SIMPLE ---|"tension"| COST

    COST --&gt; D1["Haiku over Sonnet\nKeyword pre-filter\nSkip AI for safe content"]
    ACC --&gt; D2["5 prompt variants\nStage 3 deep analysis\nHuman review for hardest"]
    SPEED --&gt; D3["Async pipeline\nEarly exit on confidence\nBackground tasks"]
    ADAPT --&gt; D4["Weighted decay\nPrompt rotation\nManual reset"]
    SIMPLE --&gt; D5["3 stages, not 10\nNo ML training\nNo Redis"]

    style COST fill:#166534,stroke:#4ade80,color:#fff
    style ACC fill:#991b1b,stroke:#f87171,color:#fff
    style SPEED fill:#854d0e,stroke:#facc15,color:#fff
    style ADAPT fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style SIMPLE fill:#1e3a5f,stroke:#60a5fa,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Our position:</strong> We optimize for <strong>cost and adaptability</strong> first, accepting slightly lower accuracy on edge cases. We compensate with human review for the cases that matter most.</p>
</section>
<section class="slide level2 smaller center">
<h2>Failure Modes</h2>
<p>We declare three scenarios where the system <strong>will</strong> fail:</p>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>1. Coordinated Novel Attack</strong></p>
<p>A new manipulation tactic not covered by any prompt variant.</p>
<p><em>Impact:</em> Harmful content passes through all 3 stages undetected.</p>
<p><em>Containment:</em> Human reviewers catch patterns → new prompt variants added manually.</p>
</div><div class="column" style="width:33%;">
<p><strong>2. Budget Exhaustion Under Attack</strong></p>
<p>Adversary floods system to burn through AI budget.</p>
<p><em>Impact:</em> Falls back to keyword-only detection — many harmful posts slip through.</p>
<p><em>Containment:</em> Rate limiting, keyword filter still catches obvious harm, escalation to humans continues.</p>
</div><div class="column" style="width:33%;">
<p><strong>3. Review Queue Saturation</strong></p>
<p>More than 20 ambiguous posts/hour during a crisis.</p>
<p><em>Impact:</em> Escalated posts wait in queue — delayed moderation.</p>
<p><em>Containment:</em> AI still provides reasoning, most harmful content caught in Stages 1-2. Queue overflow is visible on dashboard.</p>
</div></div>
</section>
<section class="slide level2 smaller center">
<h2>Tech Stack</h2>
<div class="cell" data-reveal="true" data-fig-width="11" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph Frontend["🖥️ Frontend — Next.js 16"]
        FE1["Dashboard"]
        FE2["Content Feed"]
        FE3["Review Queue"]
        FE4["System Health"]
    end

    subgraph Backend["⚙️ Backend — FastAPI"]
        BE1["Routes Layer"]
        BE2["Service Layer"]
        BE3["Background Tasks"]
    end

    subgraph External["🔌 External"]
        AI["Claude Haiku\n(Anthropic SDK)"]
        DB[("PostgreSQL 16\n(SQLAlchemy async)")]
    end

    Frontend --&gt;|"HeyAPI SDK\n+ react-query"| BE1
    BE1 --&gt; BE2
    BE2 --&gt; BE3
    BE3 --&gt; AI
    BE2 --&gt; DB

    style Frontend fill:#1e1b4b,stroke:#7c3aed,color:#fff
    style Backend fill:#166534,stroke:#4ade80,color:#fff
    style External fill:#854d0e,stroke:#facc15,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Everything runs with:</strong> <code>make up</code> + <code>make dev-frontend</code></p>
</section>
<section class="slide level2 center">
<h2>Live Dashboard</h2>
<p><strong>4 pages for full operational visibility:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Page</th>
<th>Shows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Dashboard</strong></td>
<td>Stats cards, budget progress, content by status/language, recent activity</td>
</tr>
<tr class="even">
<td><strong>Content Feed</strong></td>
<td>Submit posts, view moderation results per stage, manual escalation</td>
</tr>
<tr class="odd">
<td><strong>Review Queue</strong></td>
<td>Pending items with AI reasoning, approve/reject, hourly budget counter</td>
</tr>
<tr class="even">
<td><strong>System Health</strong></td>
<td>Detection method decay bars, cost breakdown, reset controls</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>All data refreshes every 5–10 seconds via react-query.</p>
</div>
</section>
<section class="slide level2 center">
<h2>Why This Works</h2>
<ol type="1">
<li class="fragment"><strong>Simple reasoning over complex engineering</strong> — 3 clear stages, not a black box</li>
<li class="fragment"><strong>Adaptive by design</strong> — prompt rotation + decay prevents adversary learning</li>
<li class="fragment"><strong>Cost-efficient</strong> — $14/mo of $175 budget, with graceful degradation</li>
<li class="fragment"><strong>Honest about failure</strong> — declared failure modes with containment strategies</li>
<li class="fragment"><strong>Context over classification</strong> — detects manipulation, not just keywords</li>
<li class="fragment"><strong>Human-in-the-loop, not human-dependent</strong> — 20/hr budget used only when needed</li>
</ol>
</section>
<section class="slide level2 center">
<h2></h2>
<div style="font-size: 1.8em; font-weight: bold;">
<p>“The enemy learns. Static systems fail. Only adaptive thinking survives.”</p>
</div>
<p><br></p>
<div style="font-size: 1.2em; opacity: 0.8;">
<p>Stranger Syntax — Mind-Flayer Patch v2</p>
</div>
<p><br></p>
<div style="font-size: 0.9em; opacity: 0.6;">
<p>Friends don’t lie. Thank you.</p>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Stranger Syntax — BNU Hackathon 2025</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>