"""add manipulation_tactics to moderation_results

Revision ID: a3f2702d0341
Revises: 8d5d1b6abe7b
Create Date: 2026-02-28 08:42:03.704930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f2702d0341'
down_revision: Union[str, Sequence[str], None] = '8d5d1b6abe7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_results', sa.Column('manipulation_tactics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderation_results', 'manipulation_tactics')
    # ### end Alembic commands ###
